apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "my-etcd-5"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 5
  version: "3.3.8"
  TLS:
    static:
      member:
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls

  # This will ensure the etcd pod is limited to 10.5Gi
  # My logic is we will use 10Gi for data storage and .5G for the pod
  pod:
    resources:
      limits:
        memory: 10751Mi
