apiVersion: v1
kind: Service
metadata:
  name: my-etcd-5
spec:
  type: NodePort
  ports:
    - port: 2379
      nodePort: 30379
      protocol: TCP
  selector:
    app: etcd
    etcd_cluster: my-etcd-5
---
apiVersion: v1
kind: Service
metadata:
  name: my-etcd-5-tls
spec:
  type: NodePort
  ports:
    - port: 2378
      nodePort: 30378
      protocol: TCP
  selector:
    app: etcd
    etcd_cluster: my-etcd-5
